Add locking to perclude multiple operations on one config

diff --git a/retain-sync b/retain-sync
--- a/retain-sync
+++ b/retain-sync
@@ -83,6 +83,18 @@ readConfig() {
 	formatVars
 }
 
+fileLock() {
+	# open lock file
+	exec {lockFD}>"$localDir/.retain-sync_lock"
+	flock -n $lockFD
+
+	# run if lock file was already open
+	if [[ $? -ne 0 ]]; then
+		echo "Error: another operation on this configuration is already running"
+		exit 1
+	fi
+}
+
 sshMaster() {
 	# add ControlPath to ssh defaults
 	sshOptions+=(-S "$XDG_RUNTIME_DIR/retain-sync/%C.socket")
@@ -212,6 +224,9 @@ initializeDir() {
 		# stop ssh master connection
 		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.socket "$remoteUser$remoteHost" &> /dev/null
 
+		# drop the lock on this configuration (necessary becuase of sshfs)
+		flock -u $lockFD
+
 		# inform user if initialization is interrupted
 		if [[ -f "$localDir/.retain-sync_part" ]]; then
 			printf "\nInitialization was interrupted.\n"
@@ -229,6 +244,9 @@ initializeDir() {
 		localDir="${1%/}" # remove trailing slash
 		configDir=
 	fi
+
+	# lock this configuration
+	fileLock
 
 	# don't run if finishing an interrupted initialization
 	if [[ ! -f "$localDir/.retain-sync_part" ]]; then
@@ -284,9 +302,6 @@ initializeDir() {
 
 		# read config file
 		readConfig "$1"
-
-		# format variables and set defaults
-		formatVars
 
 		# start ssh master connection
 		sshMaster
@@ -353,6 +368,9 @@ syncDir() {
 
 	# read config file
 	readConfig "$1"
+
+	# lock this configuration
+	fileLock
 
 	# start ssh master connection
 	sshMaster
@@ -608,6 +626,9 @@ retrieveDir() {
 
 	# read config file
 	readConfig "$1"
+
+	# lock this configuration
+	fileLock
 
 	# start ssh master connection
 	sshMaster
diff --git a/retain-syncd b/retain-syncd
--- a/retain-syncd
+++ b/retain-syncd
@@ -5,7 +5,7 @@ configDir="${XDG_CONFIG_HOME:-$HOME/.config}/retain-sync/$configName"
 
 # check if specified config exists
 if ! [[ -d "$configDir" ]]; then
- 	printf "\'$configName\' is not a valid configuration. Please run \'retain-sync initialize\'.\n" | \
+	printf "\'$configName\' is not a valid configuration. Please run \'retain-sync initialize\'.\n" | \
 		systemd-cat -p err -t 'retain-syncd'
 	exit 1
 fi
@@ -13,40 +13,40 @@ fi
 # source variables from config
 configError=0
 while read i; do
-    ((lineNumber++))
+	((lineNumber++))
 
-    # line is blank, skip
-    [[ "$i" =~ ^$ ]] && continue
+	# line is blank, skip
+	[[ "$i" =~ ^$ ]] && continue
 
-    # line is a comment, skip
-    [[ "$i" =~ ^# ]] && continue
+	# line is a comment, skip
+	[[ "$i" =~ ^# ]] && continue
 
-    # run if line is missing an equals sign
-    if ! [[ "$i" =~ = ]]; then
-        echo "Error: line $lineNumber of config file: unrecognized syntax"
-        ((configError++))
-    fi
+	# run if line is missing an equals sign
+	if ! [[ "$i" =~ = ]]; then
+		echo "Error: line $lineNumber of config file: unrecognized syntax"
+		((configError++))
+	fi
 
-    # parse varable
-    varName="$(echo "$i" | cut -d '=' -f 1)"
-    varValue="$(echo "$i" | cut -d '=' -f 2-)"
+	# parse varable
+	varName="$(echo "$i" | cut -d '=' -f 1)"
+	varValue="$(echo "$i" | cut -d '=' -f 2-)"
 
-    # run if option is unrecognized
-    if ! echo "$varName" | grep -qFf <(cat <<-EOF
-        localDir
-        remoteUser
-        remoteHost
-        remoteDir
-        storageLimit
-        sshfsOptions
-    EOF
-    ); then
-        printf "Error: line $lineNumber of config file: unrecognized option \'$varName\'"
-        ((configError++))
-    fi
+	# run if option is unrecognized
+	if ! echo "$varName" | grep -qFf <(cat <<-EOF
+		localDir
+		remoteUser
+		remoteHost
+		remoteDir
+		storageLimit
+		sshfsOptions
+	EOF
+	); then
+		printf "Error: line $lineNumber of config file: unrecognized option \'$varName\'"
+		((configError++))
+	fi
 
-    # declare variable
-    declare -g "$varName"="$varValue"
+	# declare variable
+	declare -g "$varName"="$varValue"
 done <"$configDir/config"
 
 # exit if there were errors in config file
@@ -72,10 +72,6 @@ mountpoint -q "$configDir/mnt" || sshfs $sshfsOptions \
 	"$remoteUser$remoteHost:$remoteDir" "$configDir/mnt" || exit 1
 
 fileWatch() {
-	# create PIDfile
-	mkdir -p "$XDG_RUNTIME_DIR/retain-sync"
-	echo "$$" > "$XDG_RUNTIME_DIR/retain-sync/retain-syncd.pid"
-
 	while true; do
 		# wait for a file to be opened
 		fileName="$(inotifywait -qre open --format '%w%f' "$localDir" "$configDir/mnt" | \
@@ -107,3 +103,7 @@ fileWatch() {
 }
 
 fileWatch &
+
+# create PIDfile
+mkdir -p "$XDG_RUNTIME_DIR/retain-sync"
+echo "$!" > "$XDG_RUNTIME_DIR/retain-sync/retain-syncd.pid"
