Tweak trash checker

diff --git a/retain-sync b/retain-sync
--- a/retain-sync
+++ b/retain-sync
@@ -201,7 +201,7 @@ initializeDir() {
 	remoteSpace=$(ssh "$remoteUser$remoteHost" 'df -B 1 "'$remoteDir'"' | tail -n 1 | awk '{print $4}')
 	localSize=$(du -sb "$localDir" | awk '{print $1}')
 	if [[ $localSize -gt $remoteSpace ]]; then
-		printf "\nError: not enough space on the server to initialize\n"
+		printf "\nError: not enough space on the server\n"
 		exit 1
 	else
 		echo "done"
@@ -216,7 +216,7 @@ initializeDir() {
 		rsync -asHAXS --exclude=".*" "$localDir/" "$remoteUser$remoteHost:$remoteDir" && \
 			echo "done" || exit 1
 	else
-		printf "\nError: remote directory isn't a valid, empty directory\n"
+		printf "\nError: remote directory isn't empty\n"
 		exit 1
 	fi
 
@@ -282,22 +282,21 @@ syncDir() {
 			# been done
 			IFS=$'\n'
 			[[ -z "${trashSums+x}" ]] && \
-				trashSums=($(find ${XDG_DATA_HOME:-$HOME/.local/share}/Trash/files \
+				trashSums=($(find "${XDG_DATA_HOME:-$HOME/.local/share}/Trash/files" \
 				-type f -print0 | xargs -0 md5sum | sort | uniq -w 32))
-
-			# compute checksum of current file
-			duplicateSums=("${trashSums[@]}")
-			duplicateSums+=($(md5sum "$configDir/mnt/$i"))
 			unset IFS
 
+			# compute checksum of current file
+			fileSum="$(md5sum "$configDir/mnt/$i")"
+
 			# test if file exists in the user's local trash directory
-			if [[ -n "$(printf "%s\n" "${duplicateSums[@]}" | sort | uniq -w 32 -d)" ]]; then
+			if [[ -n "$(printf "%s\n" "${trashSums[@]}" "$fileSum" | sort | uniq -w 32 -D)" ]]; then
 				# file is in trash, delete corresponding file on the server
 				ssh "$remoteUser$remoteHost" 'rm "'$remoteDir/$i'"' || exit 1
 			else
 				# file is not in trash, mark corresponding file on the server for deletion
-				ssh "$remoteUser$remoteHost" 'mv "'$remoteDir/$i'" "'$remoteDir'/$(dirname "'$i'")/.$(basename "'$i'").trash"' \
-					|| exit 1
+				ssh "$remoteUser$remoteHost" 'mv "'$remoteDir/$i'" "'$remoteDir'/$(dirname "'$i'")/.$(basename "'$i'").trash"' || \
+					exit 1
 			fi  
 		else
 			# new file, set priority so that it's at the top and copy to server
@@ -309,7 +308,7 @@ syncDir() {
 	echo "done"
 
 	# exit if priority.csv is empty
-	if ! grep -vq '#' "$configDir/priority.csv"; then
+	if ! grep -vq '^#' "$configDir/priority.csv"; then
 		echo "Local directory is empty. There is nothing else to do."
 		exit 0	
 	fi
@@ -463,8 +462,8 @@ syncDir() {
 	# make all paths in directory priority file relative
 	sed -i "s|$configDir/mnt/||" $dirPriorityFile
 
-	# sync (download) directories that are in the directory priority file but
-	# not stored locally
+	# download directories that are in the directory priority file but not stored
+	# locally
 	printf "Downloading new files... "
 	while read i; do
 		if find "$localDir" -mindepth 1 -not -path '*/\.*' -type l | grep -Fq "$localDir/$i"; then
