Replace getopt with custom solution

diff --git a/retain-sync b/retain-sync
--- a/retain-sync
+++ b/retain-sync
@@ -615,7 +615,7 @@ syncDir() {
 			dirPriority=0
 		else
 			# Note: '10485760' (10MiB) was arbitrarily picked to make the resulting
-			# numbers easier to work with.
+			# numbers easier to work with
 			dirPriority=$(echo "scale=6; ${dirPriority:-0}/($dirSize/10485760)" | bc)
 		fi
 
@@ -711,6 +711,8 @@ syncDir() {
 				# error with bc
 				currentFileSize=16
 			fi
+			# Note: '10485760' (10MiB) was arbitrarily picked to make the resulting
+			# numbers easier to work with
 			adjustedPriority=$(echo "scale=6; $(rev <<< "${noSyncSorted[$i]}" | \
 				cut -d ',' -f 1 | rev)/($currentFileSize/10485760)" | bc)
 			noSyncSorted[$i]="$(sed "s/,[0-9\.]*$/,$adjustedPriority/" <<< "${noSyncSorted[$i]}")"
@@ -949,49 +951,67 @@ agePriority() {
 }
 
 # parse global options
-optString=$(getopt -l help -n 'retain-sync' -- "$@")
-eval set -- "$optString"
+for ((i=1; i<=$#; i++)); do
+	# Note: getopt isn't being used here because getopt doesn't allow for
+	# parameters to have their own options
 
-# read options
-while true; do
+	# if parameter is multiple short options sandwitched together, separate them
+	if [[ "${@:$i:1}" =~ ^-[^-\ ]{2,} ]]; then
+		set -- ${@:1:$((i-1))} $(sed -e 's/\(\w\)/ -\1/g' -e 's/^- //' <<< "${@:$i:1}") ${@:$((i+1))}
+	# if parameter is a long option with an argument separated by an equals
+	# sign, replace the equals sign with a space
+	elif [[ "${@:$i:1}" =~ ^--[^-\ ] ]]; then
+		set -- ${@:1:$((i-1))} $(sed -e 's/=/ /' <<< "${@:$i:1}") ${@:$((i+1))}
+	fi
+done
+
+# read global options
+while [[ "$1" =~ ^- ]]; do
 	case "$1" in
 		--help)
 			printHelp
 			exit ;;
-		--)
-			shift
-			break ;;
 		*)
-			>&2 "Error: invalid argument"
+			>&2 echo "Error: unknown option"
+			>&2 printf "Try \'retain-sync --help\' for more information.\n"
 			exit 1 ;;
 	esac
 done
 
-# read commands
+# read subcommands
 case "$1" in
 	'')
 		>&2 echo "Error: missing argument"
-		printHelp
+		>&2 printf "Try \'retain-sync --help\' for more information.\n"
 		exit 1 ;;
 	initialize)
 		shift
 
 		# parse options
-		optString=$(getopt -o e: -l exclude: -n 'retain-sync' -- "$@")
-		eval set -- "$optString"
+		for ((i=1; i<=$#; i++)); do
+			# Note: getopt isn't being used here because getopt doesn't allow for
+			# parameters to have their own options
 
-		# read options into variables
-		while true; do
+			# if parameter is multiple short options sandwitched together, separate them
+			if [[ "${@:$i:1}" =~ ^-[^-\ ]{2,} ]]; then
+				set -- ${@:1:$((i-1))} $(sed -e 's/\(\w\)/ -\1/g' -e 's/^- //' <<< "${@:$i:1}") ${@:$((i+1))}
+			# if parameter is a long option with an argument separated by an equals
+			# sign, replace the equals sign with a space
+			elif [[ "${@:$i:1}" =~ ^--[^-\ ] ]]; then
+				set -- ${@:1:$((i-1))} $(sed -e 's/=/ /' <<< "${@:$i:1}") ${@:$((i+1))}
+			fi
+		done
+
+		# read options
+		while [[ "$1" =~ ^- ]]; do
 			case "$1" in
 				-e|--exclude)
 					optExclude=1
 					optExcludeFile="$2"
 					shift 2 ;;
-				--)
-					shift
-					break ;;
 				*)
-					>&2 echo "Error: invalid argument"
+					>&2 echo "Error: unknown option"
+					>&2 printf "Try \'retain-sync --help\' for more information.\n"
 					exit 1 ;;
 			esac
 		done
@@ -1009,6 +1029,6 @@ case "$1" in
 		agePriority "$2" ;;
 	*)
 		>&2 printf "Error: \'$1\' is not a valid command\n"
-		printHelp
+		>&2 printf "Try \'retain-sync --help\' for more information.\n"
 		exit 1 ;;
 esac
