Make commands fail if sshfs is unmounted

diff --git a/common/retain-sync.in b/common/retain-sync.in
--- a/common/retain-sync.in
+++ b/common/retain-sync.in
@@ -146,7 +146,7 @@ readConfig() {
 	remoteDir="${remoteDirIn%/}"
 	storageLimit="$(sed -r -e 's/KB?/\*1024/' -e 's/MB?/\*1048576/' \
 		-e 's/GB?/\*1073741824/' <<< "$storageLimitIn" | bc)"
-	sshfsOptions=(-o "$sshfsOptions" -p "$portIn")
+	sshfsOptions=(-o "$sshfsOptions" -o "nonempty" -p "$portIn")
 	deleteAlways="${deleteAlways,,}"
 	syncExtraFiles="${syncExtraFiles,,}"
 	inflatePriority="${inflatePriority,,}"
@@ -171,7 +171,7 @@ fileLock() {
 
 sshMaster() {
 	# add ControlPath to ssh defaults
-	sshOptions+=(-S "$XDG_RUNTIME_DIR/retain-sync/%C.socket")
+	sshOptions+=(-S "$XDG_RUNTIME_DIR/retain-sync/%C.sock")
 
 	# create runtime dir if it doesn't already exist
 	mkdir -p "$XDG_RUNTIME_DIR/retain-sync"
@@ -324,7 +324,7 @@ initializeDir() {
 
 	cleanup() {
 		# stop ssh master connection
-		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.socket "$remoteUser$remoteHost" &> /dev/null
+		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.sock "$remoteUser$remoteHost" &> /dev/null
 
 		# drop the lock on this configuration (necessary becuase of sshfs)
 		flock -u 200
@@ -419,7 +419,7 @@ initializeDir() {
 		remoteUser="${remoteUserIn:+$remoteUserIn@}"
 		remoteHost="$remoteHostIn"
 		remoteDir="${remoteDirIn%/}"
-		sshfsOptions=(-o "$sshfsOptions" -p "$portIn")
+		sshfsOptions=(-o "$sshfsOptions" -o "nonempty" -p "$portIn")
 
 		# escape paths for use in sed substitutions
 		localDirEsc="$(sed 's/[][()\.^$?*+]/\\&/g' <<< "$localDir")"
@@ -509,14 +509,20 @@ initializeDir() {
 		--exclude-from="$configDir/exclude" "$localDir/" \
 		"$remoteUser$remoteHost:$remoteDir" && echo "done" || exit 1
 
+	# Note: the purpose of this directory is to ensure that any commands that interact
+	# with it (e.g. find $configDir/mnt/.dest/..) fail when sshfs isn't mounted
+	mkdir -p "$configDir/mnt/.dest"
+	chmod 000 "$configDir/mnt/.dest"
+
 	# mount sshfs
-	mkdir -p "$configDir/mnt"
 	mountpoint -q "$configDir/mnt" || sshfs "${sshfsOptions[@]}" \
 		"$remoteUser$remoteHost:$remoteDir" "$configDir/mnt"
 	if [[ $? -ne 0 ]]; then
 		>&2 echo "Error: unable to mount remote directory over sshfs"
 		exit 1
 	fi
+
+	mkdir "$configDir/mnt/.dest"
 
 	# replace local files with symlinks unless local directory is empty
 	if [[ -n "${localFiles[@]}" ]]; then
@@ -527,8 +533,8 @@ initializeDir() {
 	# create priority.csv file containing a list of all files in the tree followed
 	# by a starting priority of zero
 	echo "# Editing this file by hand is not recommended." > "$configDir/priority.csv"
-	find "$configDir/mnt" -not -type d -exec echo '{},0' \; | \
-		sed -r "s|$configDirEsc/mnt||" >> "$configDir/priority.csv"
+	find "$configDir/mnt/.dest/.." -not -type d -exec echo '{},0' \; | \
+		sed -r "s|$configDirEsc/mnt/\.dest/\.\.||" >> "$configDir/priority.csv" || exit 1
 
 	# create "init" file used to indicate that the directory has been initialized and
 	# what the name of its config is
@@ -542,7 +548,7 @@ initializeDir() {
 syncDir() {
 	cleanup() {
 		# stop ssh master connection
-		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.socket "$remoteUser$remoteHost" &> /dev/null
+		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.sock "$remoteUser$remoteHost" &> /dev/null
 
 		# drop the lock on this configuration (necessary becuase of sshfs)
 		flock -u 200
@@ -580,7 +586,7 @@ syncDir() {
 	fi
 
 	# umount sshfs if mountpoint is broken
-	mkdir -p "$configDir/mnt" 2> /dev/null
+	mkdir -p "$configDir/mnt/.dest" 2> /dev/null
 	[[ ! -d "$configDir/mnt" ]] && fusermount -u "$configDir/mnt"
 
 	# mount sshfs if not already mounted
@@ -651,28 +657,20 @@ syncDir() {
 				unset IFS
 
 				# compute checksum of current file
-				fileSum="$(md5sum "$configDir/mnt$i")"
+				fileSum="$(md5sum "$configDir/mnt/.dest/..$i")"
 
 				# test if file exists in the user's local trash directory by comparing checksums
 				if [[ -n "$(printf "%s\n" "${trashSums[@]}" "$fileSum" | sort | uniq -w 32 -D)" ]]; then
 					# file is in trash, delete corresponding file on the server
-
-					# Note: we are going through the mountpoint becuase deleting the file using the
-					# ssh command causes sshfs to pretend that the file is still there until someone
-					# actually looks inside the mountpoint to update it
-					rm "$configDir/mnt$i" || exit 1
+					rm "$configDir/mnt/.dest/..$i" || exit 1
 				else
 					# file is not in trash, mark corresponding file on the server for deletion
-					mv "$configDir/mnt$i" \
-						"$configDir/mnt$(dirname "$i")/.$(basename "$i").trash" || exit 1
+					mv "$configDir/mnt/.dest/..$i" \
+						"$configDir/mnt/.dest/..$(dirname "$i")/.$(basename "$i").trash" || exit 1
 				fi
 			else
 				# $deleteAlways is set to 'yes', delete corresponding file on the server
-
-				# Note: we are going through the mountpoint becuase deleting the file using the
-				# ssh command causes sshfs to pretend that the file is still there until someone
-				# actually looks inside the mountpoint to update it
-				rm "$configDir/mnt$i" || exit 1
+				rm "$configDir/mnt/.dest/..$i" || exit 1
 			fi
 		else
 			# new file
@@ -714,7 +712,7 @@ syncDir() {
 
 	# upload new files and files that have changed since the last sync
 	rsync -aHAXSu --exclude-from="$configDir/exclude" --exclude=".*" --safe-links \
-		"$localDir/" "$configDir/mnt"
+		"$localDir/" "$configDir/mnt/.dest/.." || exit 1
 
 	echo "done"
 
@@ -723,7 +721,8 @@ syncDir() {
 	# create directory priority file containing a list of all directories in the
 	# tree
 	dirPriorityFile="$(mktemp)"
-	find "$configDir/mnt" -mindepth 1 -type d | sed -r "s|$configDirEsc/mnt||" > "$dirPriorityFile"
+	find "$configDir/mnt/.dest/.." -mindepth 1 -type d | sed -r \
+		"s|$configDirEsc/mnt/\.dest/\.\.||" > "$dirPriorityFile" || exit 1
 
 	# read directory priority file line-by-line
 	while read -r i; do
@@ -734,7 +733,7 @@ syncDir() {
 			awk '{print "scale=6; " $0}'| bc) 2> /dev/null
 
 		# get the size of the directory in bytes
-		dirSize="$(du -sb "$configDir/mnt$i" | awk '{print $1}')"
+		dirSize="$(du -sb "$configDir/mnt/.dest/..$i" | awk '{print $1}')" || exit 1
 
 		# set minimum dir size of 16 bytes to perclude a "divide by zero"
 		# error with bc
@@ -763,7 +762,7 @@ syncDir() {
 		syncSize=0
 
 		while read -r i; do
-			dirSize="$(du -sb "$configDir/mnt$i" | awk '{print $1}')"
+			dirSize="$(du -sb "$configDir/mnt/.dest/..$i" | awk '{print $1}')" || exit 1
 
 			if [[ "$dirSize" -gt $storageLimit ]]; then
 				# current directory alone is larger than the storage limit, remove from
@@ -792,8 +791,8 @@ syncDir() {
 				else
 					# total list size is still within the storage limit
 
-					dirPriorityTree+=($(find "$configDir/mnt$i" -mindepth 1 -type d | \
-						sed -r "s|$configDirEsc/mnt||"))
+					dirPriorityTree+=($(find "$configDir/mnt/.dest/..$i" -mindepth 1 -type d | \
+						sed -r "s|$configDirEsc/mnt/\.dest/\.\.||")) || exit 1
 
 					# check if the while loop has reached the last line of the directory
 					# priority file
@@ -818,11 +817,11 @@ syncDir() {
 	# get list of individual files that aren't included in the directory priority file
 	printf "%s" "Sorting remaining files by priority... "
 	IFS=$'\n'
-	noSyncFiles=($(find "$configDir/mnt" -not -name '.*.trash' -not -type d | \
-		sed -r "s|$configDirEsc/mnt||"))
+	noSyncFiles=($(find "$configDir/mnt/.dest/.." -not -name '.*.trash' -not -type d | \
+		sed -r "s|$configDirEsc/mnt/\.dest/\.\.||")) || exit 1
 	while read -r i; do
-		noSyncFiles+=($(find "$configDir/mnt$i" -not -name '.*.trash' -not -type d | \
-			sed -r "s|$configDirEsc/mnt||"))
+		noSyncFiles+=($(find "$configDir/mnt/.dest/..$i" -not -name '.*.trash' -not \
+			-type d | sed -r "s|$configDirEsc/mnt/\.dest/\.\.||")) || exit 1
 	done <"$dirPriorityFile"
 	noSyncFiles=($(printf "%s\n" "${noSyncFiles[@]}" | sort | uniq -u))
 
@@ -839,7 +838,8 @@ syncDir() {
 		# adjust priority for file size
 		for i in "${!noSyncSorted[@]}"; do
 			currentFile="$(rev <<< "${noSyncSorted[$i]}" | cut -d ',' -f 2- | rev)"
-			currentFileSize=$(du -sb "$configDir/mnt$currentFile" | awk '{print $1}')
+			currentFileSize=$(du -sb "$configDir/mnt/.dest/..$currentFile" | \
+				awk '{print $1}') || exit 1
 
 			# set minimum file size of 16 bytes to perclude a "divide by zero"
 			# error with bc
@@ -851,7 +851,8 @@ syncDir() {
 			# numbers easier to work with
 			adjustedPriority=$(echo "scale=6; $(rev <<< "${noSyncSorted[$i]}" | \
 				cut -d ',' -f 1 | rev)/($currentFileSize/10485760)" | bc)
-			noSyncSorted[$i]="$(sed "s/,[0-9\.]*$/,$adjustedPriority/" <<< "${noSyncSorted[$i]}")"
+			noSyncSorted[$i]="$(sed "s/,[0-9\.]*$/,$adjustedPriority/" <<< \
+				"${noSyncSorted[$i]}")"
 		done
 
 		# sort files by priority
@@ -860,7 +861,8 @@ syncDir() {
 		unset IFS
 
 		for i in "${noSyncSorted[@]}"; do
-			currentFileSize=$(du -sb "$configDir/mnt$i" | awk '{print $1}')
+			currentFileSize=$(du -sb "$configDir/mnt/.dest/..$i" | \
+				awk '{print $1}') || exit 1
 
 			# get size of current file in bytes and add it to the total size
 			((syncSize+=currentFileSize))
@@ -898,8 +900,9 @@ syncDir() {
 	cp -asn "$configDir"/mnt/* "$localDir" &> /dev/null
 
 	# remove symlinks to files marked for deletion
-	find "$configDir/mnt" -not -type d -name '.*.trash' | \
-		sed -r "s|$configDirEsc/mnt|$localDir|" | xargs -d '\n' rm -f
+	find "$configDir/mnt/.dest/.." -not -type d -name '.*.trash' | \
+		sed -r "s|$configDirEsc/mnt/\.dest/\.\.|$localDir|" | xargs -d '\n' rm -f || \
+			exit 1
 
 	# remove empty directories
 	find "$localDir" -not -path '*/\.*' -type d -empty -delete
@@ -908,31 +911,31 @@ syncDir() {
 	printf "%s" "Downloading new files... "
 
 	# download (and remove from the server) excluded files that are still on the server
-	find "$configDir/mnt" -not -type d | sed -r "s|$configDirEsc/mnt||" | \
-		grep -Fxf <(printf "%s\n" "${excludeFiles[@]}" | sed -r "s|$localDirEsc||") | \
-		rsync -e "ssh ${sshOptions[*]}" -asHAXS --files-from=- --remove-source-files \
-		"$remoteUser$remoteHost:$remoteDir/" "$localDir" || exit 1
+	find "$configDir/mnt/.dest/.." -not -type d | sed -r \
+		"s|$configDirEsc/mnt/\.dest/\.\.||" | grep -Fxf <(printf "%s\n" \
+		"${excludeFiles[@]}" | sed -r "s|$localDirEsc||") | rsync -asHAXS \
+		--files-from=- --remove-source-files "$configDir/mnt/.dest/../" \
+		"$localDir" || exit 1
 
 	# find file paths in directory priority file
 	IFS=$'\n'
 	while read -r i; do
-		downloadFiles+=($(find "$configDir/mnt$i" -not -type d -not -name '.*.trash' | \
-			sed -r "s|$configDirEsc/mnt||"))
+		downloadFiles+=($(find "$configDir/mnt/.dest/..$i" -not -type d -not -name \
+			'.*.trash' | sed -r "s|$configDirEsc/mnt||")) || exit 1
 	done <"$dirPriorityFile"
 	unset IFS
 
 	# download directories that are in the directory priority file but not stored
 	# locally
-	printf "%s\n" "${downloadFiles[@]}" | rsync -e "ssh ${sshOptions[*]}" -asHAXS \
-		--files-from=- --exclude-from="$configDir/exclude" \
-		"$remoteUser$remoteHost:$remoteDir/" "$localDir" || exit 1
+	printf "%s\n" "${downloadFiles[@]}" | rsync -asHAXS --files-from=- \
+		--exclude-from="$configDir/exclude" "$configDir/mnt/.dest/../" "$localDir" || \
+		exit 1
 
 	if [[ "$syncExtraFiles" == "yes" ]]; then
-		# fill the remaining space with the highest-priority individual files that haven't
-		# already been downloaded
-		printf "%s\n" "${extraFiles[@]}" | \
-			rsync -e "ssh ${sshOptions[*]}" -asHAXS --files-from=- \
-			"$remoteUser$remoteHost:$remoteDir/" "$localDir" || exit 1
+		# fill the remaining space with the highest-priority individual files that
+		# haven't already been downloaded
+		printf "%s\n" "${extraFiles[@]}" | rsync -asHAXS --files-from=- \
+			"$configDir/mnt/.dest/../" "$localDir" || exit 1
 	fi
 	echo "done"
 }
@@ -940,7 +943,7 @@ syncDir() {
 retrieveDir() {
 	cleanup() {
 		# stop ssh master connection
-		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.socket "$remoteUser$remoteHost" &> /dev/null
+		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.sock "$remoteUser$remoteHost" &> /dev/null
 	}
 
 	# read config file
@@ -1004,8 +1007,9 @@ retrieveDir() {
 	if mountpoint -q "$configDir/mnt" || [[ ! -d "$configDir/mnt" ]]; then
 		fusermount -u "$configDir/mnt" || exit 1
 	fi
-	rm -f "$localDir/.retain-sync_init" "$localDir/.retain-sync_part"
-	rm -f "$localDir/.retain-sync_lock"
+	rm -f "$localDir/.retain-sync_init" "$localDir/.retain-sync_part" \
+		"$localDir/.retain-sync_lock"
+	chmod 700 "$configDir/mnt/.dest"
 	rm -r "$configDir"
 	echo "done"
 }
@@ -1051,7 +1055,7 @@ listConfigs() {
 emptyTrash() {
 	cleanup() {
 		# stop ssh master connection
-		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.socket "$remoteUser$remoteHost" &> /dev/null
+		ssh -O exit -S "$XDG_RUNTIME_DIR"/retain-sync/%C.sock "$remoteUser$remoteHost" &> /dev/null
 	}
 
 	# read config file
